[helpers]

[default]
depends = ["zsh", "nvim", "git", "systemd", "foot", "atuin", "kitty"]

[default.files]

[default.variables]

[zsh.files]
zshrc = "~/.zshrc"
zimrc = "~/.zimrc"

[atuin.files]
atuin = "~/.config/atuin/config.toml"

[nvim]
files.nvim = { target = "~/.config/nvim", type = "symbolic", recurse = false }

[git.files]
git = "~/.config/git/config"

[latex.files]
latexmkrc = "~/.config/latexmk/latexmkrc"

[systemd.files]
systemd = "~/.config/systemd/user"

[kitty.files]
kitty = "~/.config/kitty/kitty.conf"

[foot.files]
