[helpers]

[default]
depends = ["zsh", "nvim", "git", "systemd"]

[default.files]

[default.variables]

[zsh.files]
zshrc = "~/.zshrc"

[nvim]
files.nvim = { target = "~/.config/nvim", type = "symbolic" }

[git.files]
git = "~/.config/git/config"

[latex.files]
latexmkrc = "~/.config/latexmk/latexmkrc"

[systemd.files]
systemd = "~/.config/systemd/user"
